name: 'ECS Deploy Runner Invoker'
description: 'Invoke the ECS Deploy Runner from a GitHub Actions workflow'
inputs:
  gruntwork-installer-version:
    description: 'gruntwork-installer version'
    required: true
    default: 'v0.0.34'
  terraform-aws-ci-version:
    description: 'terraform-aws-ci version'
    required: true
    default: 'v0.29.10'
  terraform-aws-security-version:
    description: 'terraform-aws-security version'
    required: true
    default: 'v0.44.10'
  main-branch-name:
    description: 'Name of the main branch of the repository'
    required: true
    default: 'main'
  command:
    description: 'Command to run (plan/apply/docker-image-build)'
    required: true
  build_args:
    description: 'Build time arguments to use when building Docker images'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - id: set-friendly-ref
      run: |
        if [[ ! -z "$GITHUB_HEAD_REF" ]]; then
          echo 'FRIENDLY_REF=${{ github.event.pull_request.head.ref }}' >> $GITHUB_ENV
        else
          echo 'FRIENDLY_REF=$GITHUB_REF' >> $GITHUB_ENV
        fi
      shell: bash
    - id: install-helpers
      run: ${{ github.action_path }}/helpers/install.sh ${{ inputs.gruntwork-installer-version }} ${{ inputs.terraform-aws-ci-version }} ${{ inputs.terraform-aws-security-version }}
      shell: bash
    - id: run-command
      run: ${{ github.action_path }}/helpers/deploy.sh ${{ env.AWS_ACCOUNT_ID }} ${{ env.AWS_REGION }} ${{ github.repository }}.git ${{ env.FRIENDLY_REF }} ${{ inputs.command }} '${{ inputs.build_args }}'
      shell: bash
